In [108]:
f=open("/Users/divyamsharma/Desktop/TrumpSpeechTrain.txt","rb")
Train_Data=f.read()
Train_Data=str(Train_Data)



Reading Training Data From File 1 and converting bytes to str

In [109]:
f1=open("/Users/divyamsharma/Desktop/TrumpSpeechTest.txt","rb")
Test_Data=f1.read()
Test_Data=str(Test_Data)


Reading Testing Data From File 2 and converting bytes to str

In [110]:
Train_Sentences=Train_Data.split('.')
Test_Sentences=Test_Data.split('.')


Converting Str type files into a list of sentences

In [111]:
Train_Sentence_Lengths=[]
for i in Train_Sentences:
    Train_Sentence_Lengths.append(len(i.split()))
Test_Sentence_Lengths=[]
for i in Test_Sentences:
    Test_Sentence_Lengths.append(len(i.split()))

Making Lists of lengths of Training and Testing Sentences

In [112]:
def TuneData(Sentence_Lengths):
    X=[]
    Y=[]
    for i in range(0,len(Sentence_Lengths)-5,1):
        X.append([Sentence_Lengths[i],Sentence_Lengths[i+1],Sentence_Lengths[i+2],Sentence_Lengths[i+3],Sentence_Lengths[i+4]])
        if(Sentence_Lengths[i+5]>10):
            Y.append(1)
        else:
            Y.append(0)
            
    return X,Y

This Function manipulates the input data in such a way that the returned X is a list of 5 consecutive sentences and Y is length of the 6th sentences. So, I am using the length of 6th sentence as a target for training my model

In [113]:
X_train,Y_train=TuneData(Train_Sentence_Lengths)
X_test,Y_test=TuneData(Test_Sentence_Lengths)



Putting my training and testing data to tune.

In [114]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X_train, Y_train)
Y_pred = clf.predict(X_test)
print(classification_report(Y_test,Y_pred))
print(confusion_matrix(Y_test,Y_pred))

             precision    recall  f1-score   support

          0       0.00      0.00      0.00        28
          1       0.64      0.98      0.77        50

avg / total       0.41      0.63      0.49        78

[[ 0 28]
 [ 1 49]]


In [115]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X_train, Y_train)
Y_pred = clf.predict(X_test)
print(classification_report(Y_test,Y_pred))
print(confusion_matrix(Y_test,Y_pred))

             precision    recall  f1-score   support

          0       0.33      0.21      0.26        28
          1       0.63      0.76      0.69        50

avg / total       0.53      0.56      0.54        78

[[ 6 22]
 [12 38]]


In [116]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X_train, Y_train)
Y_pred = clf.predict(X_train)
print(classification_report(Y_train,Y_pred))
print(confusion_matrix(Y_train,Y_pred))

             precision    recall  f1-score   support

          0       0.43      0.26      0.32       113
          1       0.63      0.79      0.70       185

avg / total       0.56      0.59      0.56       298

[[ 29  84]
 [ 39 146]]


In [119]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X_train, Y_train)
Y_pred = clf.predict(X_train)
print(classification_report(Y_train,Y_pred))
print(confusion_matrix(Y_train,Y_pred))

             precision    recall  f1-score   support

          0       0.43      0.05      0.09       113
          1       0.62      0.96      0.75       185

avg / total       0.55      0.61      0.50       298

[[  6 107]
 [  8 177]]


In [122]:
import numpy as np
np.savetxt("SentencePrediction.csv",Y_pred,fmt="%.5f")
np.savetxt("SentenceTrue.csv",Y_test,fmt="%.5f")
